spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <google-client-id>
            clientSecret: <google-client-secret>
          facebook:
            clientId: <facebook-client-id>
            clientSecret: <facebook-client-secret>